repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
        exclude: ^mkdocs\.yml$
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/tcort/markdown-link-check
    rev: v3.14.2
    hooks:
    - id: markdown-link-check
      args: [-q]
      files: ^(README\.md|docs/.*\.md)$
