site_name: Josef's Projects
site_url: https://JosefGst.github.io
theme: 
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
        
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - navigation.search.highlight
    - navigation.search.suggest
    - navigation.search.share
    - navigation.search.suggest
    - navigation.search.share
    - naviagtion.footer
nav:
  - Home: index.md
  - Projects:
    - blog/index.md

plugins:
  - blog:
      draft: false
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - electronics

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:gstoettnerjo@gmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/JosefGst
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/josef-gstoettner-437630172/
    - icon: fontawesome/solid/rss
      name: Josef's blog on RSS
      link: https://josefgst.github.io/feed_rss_created.xml